### ISSUE TITLE
Undirected weighted graph reports weight for one direction only

### ISSUE THREAD

**Issue by dkvasnicka** [stchang/graph#18]
I have a graph created using `(weighted-graph/undirected '())` and `add-edge!`. When I do `edge-weight` I only get the weight for the direction I used when calling `add-edge!`. For the other dir I get `+inf.0`.
I ended up calling `add-edge!` twice for every edge to make my program work correctly. Is this OK and if so, what is the rationale?
Anyway, cool lib otherwise :) Makes graph-based algos short and sweet.

**Comment by stchang** [comment]
Thanks a bug, thanks for the report!
