### ISSUE TITLE
transitive-closure silently breaks documented contract in case of empty graph

### ISSUE THREAD

**Issue by v-for-vincent** [stchang/graph#21]
When I create an empty graph and compute the transitive closure, the result is `#f` even though the documentation does not list this as an option. There is no contract error.

How to reproduce:

    (require graph)
    (define my-graph (directed-graph (list)))
    (transitive-closure my-graph)

**Comment by stchang** [comment]
Yes, you're right. It should return an empty hash for an empty graph input. Fixing it now.

**Comment by stchang** [comment]
Thanks for the report!

**Comment by v-for-vincent** [comment]
Thanks for a really useful library!
