### ISSUE TITLE
depends on racket-doc

### ISSUE THREAD

**Issue by clacke** [stchang/graph#35]
For people who are using racket-minimal it would be really nice if `graph` could depend on `graph-lib` and `graph-doc`, where only `graph-lib` would be necessary for compiling depending code, and only `graph-doc` would depend on the heavy and circular `racket-doc`.

**Comment by clacke** [comment]
By circular I mean, racket-doc is involved in a circular dependency of 42 packages, which all need to be installed together and cannot be installed separately, and those packages in turn transitively depend on another 90 packages, so it's quite a noticeable chunk.

I'm willing to make the PR, if you don't see any problem with it.

**Comment by stchang** [comment]
> I'm willing to make the PR, if you don't see any problem with the idea.

That would be great! This is a good idea, thanks.
