### ISSUE TITLE
Allow setting of graphviz attributes other than color

### ISSUE THREAD

**Issue by urbanslug** [stchang/graph#45]
What do you think of adding a way to let the user set any set of attributes to their dot format output other than color. In my case I'd like box for the node shape.

For example: (source [wikipedia](https://en.wikipedia.org/wiki/DOT_%28graph_description_language%29#Attributes))

```dot
graph graphname {
     // This attribute applies to the graph itself
     size="1,1";
     // The label attribute can be used to change the label of a node
     a [label="Foo"];
     // Here, the node shape is changed.
     b [shape=box];
     // These edges both have different line properties
     a -- b -- c [color=blue];
     b -- d [style=dotted];
     // [style=invis] hides a node.
   }
```

**Comment by stchang** [comment]
I believe https://github.com/stchang/graph/pull/65 addresses all the issues here? (re-open if it doesnt)
