### ISSUE TITLE
graphviz: support arbitrary edge values

### ISSUE THREAD

**Issue by stchang** [stchang/graph#53]

**Comment by stchang** [comment]
see discussions here: https://groups.google.com/d/topic/racket-users/2ea5zaD5NrU/discussion

**Comment by scolobb** [comment]
@stchang I made pull request implementing your suggestion to replace `=` with `equal?` and doing a couple other small changes: https://github.com/stchang/graph/pull/54

**Comment by stchang** [comment]
Added in https://github.com/stchang/graph/commit/fb3c144665f2384f8b5013f9472e688aca8e9674

Thanks again!
