### ISSUE TITLE
`undirected-graph` raises `apply` error

### ISSUE THREAD

**Issue by rfindler** [stchang/graph#56]
This misuse of `undirected-graph` should raise an error about its argument but fails internally.

```
> (undirected-graph (list #f #t) (list 0 1))
. . apply: contract violation
  expected: list?
  given: #f
```

**Comment by stchang** [comment]
thanks! should definitely be fixed

**Comment by rfindler** [comment]
I just double checked and I don't think it is fixed. I'm at `ba621328a26803c72a0d3890aaa5ac81c166f117` and I still see the same error message. I you sure this has been fixed?

**Comment by stchang** [comment]
sorry, i meant that it's definitely bad and will be fixed soon!

**Comment by rfindler** [comment]
Thanks!
